language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="3e310a22-8c97-4ea6-864d-d20ccb24ee75"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -rvk12@bk.ru
    on_success: never # default: change
    on_failure: always # default: always